In [2]:
# Task 1: Data Cleaning and Preprocessing

In [36]:
# Load the Raw Dataset
import pandas as pd

df = pd.read_csv('/content/consumer_electronics_sales_data.csv')

In [37]:
 #Inspect the Data

In [38]:
print(df.dtypes)

productid                int64
productcategory         object
productbrand            object
productprice            object
customerage              int64
customergender          object
purchasefrequency        int64
customersatisfaction     int64
purchaseintent           int64
dtype: object

In [39]:
print(df.head())

   productid productcategory  productbrand                   productprice  \
0       5874     Smartphones  Other Brands  1970-01-01 00:00:00.000000312
1       5875   Smart Watches       Samsung  1970-01-01 00:00:00.000000980
2       5876         Tablets       Samsung  1970-01-01 00:00:00.000002606
3       5877     Smartphones       Samsung  1970-01-01 00:00:00.000000870
4       5878         Tablets          Sony  1970-01-01 00:00:00.000001798

   customerage customergender  purchasefrequency  customersatisfaction  \
0           18           Male                  2                     1
1           35         Female                  7                     2
2           63           Male                  1                     5
3           63         Female                 10                     3
4           57           Male                 17                     3

   purchaseintent
0               0
1               1
2               1
3               1
4               0

In [40]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   productid             9000 non-null   int64
 1   productcategory       9000 non-null   object
 2   productbrand          9000 non-null   object
 3   productprice          9000 non-null   object
 4   customerage           9000 non-null   int64
 5   customergender        9000 non-null   object
 6   purchasefrequency     9000 non-null   int64
 7   customersatisfaction  9000 non-null   int64
 8   purchaseintent        9000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 632.9+ KB
None

In [41]:
print(df.describe())

          productid  customerage  purchasefrequency  customersatisfaction  \
count   9000.000000  9000.000000        9000.000000           9000.000000
mean   10373.500000    43.347000          10.054667              2.996000
std     2598.220545    15.055084           5.461328              1.405301
min     5874.000000    18.000000           1.000000              1.000000
25%     8123.750000    30.000000           5.000000              2.000000
50%    10373.500000    43.000000          10.000000              3.000000
75%    12623.250000    56.000000          15.000000              4.000000
max    14873.000000    69.000000          19.000000              5.000000

       purchaseintent
count     9000.000000
mean         0.566444
std          0.495593
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          1.000000

In [42]:
#Check for Missing Values
print(df.isnull().sum())   # Count missing values per column

productid               0
productcategory         0
productbrand            0
productprice            0
customerage             0
customergender          0
purchasefrequency       0
customersatisfaction    0
purchaseintent          0
dtype: int64

In [46]:
# Remove Duplicates
df.drop_duplicates(inplace=True)

In [48]:
print(df['customergender'].unique())

['Male' 'Female']

In [49]:
df['customergender'] = df['customergender'].map({0: 'Male', 1: 'Female'})

In [51]:
df['customergender'] = df['customergender'].str.capitalize()

In [22]:
print(df.columns)

Index(['ProductID', 'ProductCategory', 'ProductBrand', 'ProductPrice',
       'CustomerAge', 'CustomerGender', 'PurchaseFrequency',
       'CustomerSatisfaction', 'PurchaseIntent'],
      dtype='object')

In [24]:
df['ProductPrice'] = pd.to_datetime(df['ProductPrice'])

In [25]:
# Rename Columns
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [68]:
#fix datatype
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [69]:
df['customerage'] = pd.to_numeric(df['customerage'], errors='coerce')
df['productprice'] = pd.to_numeric(df['productprice'], errors='coerce')

In [72]:
df['productprice'] = pd.to_datetime(df['productprice'], format='%d-%m-%Y', errors='coerce')
print(df.dtypes)

productid                        int64
productcategory                 object
productbrand                    object
productprice            datetime64[ns]
customerage                      int64
customergender                  object
purchasefrequency                int64
customersatisfaction             int64
purchaseintent                   int64
dtype: object

In [31]:
#Save the Cleaned Dataset
df.to_csv('consumer_electronics_sales_data.csv', index=False)

In [66]:
print(df[df['purchasefrequency'] < 5])

      productid productcategory  productbrand  productprice  customerage  \
0          5874     Smartphones  Other Brands           NaN           18
2          5876         Tablets       Samsung           NaN           63
8          5882         Laptops  Other Brands           NaN           19
10         5884     Smartphones  Other Brands           NaN           20
12         5886         Tablets       Samsung           NaN           48
...         ...             ...           ...           ...          ...
8972      14846     Smartphones          Sony           NaN           62
8976      14850      Headphones          Sony           NaN           31
8991      14865   Smart Watches  Other Brands           NaN           35
8994      14868         Laptops          Sony           NaN           44
8998      14872         Tablets            HP           NaN           38

     customergender  purchasefrequency  customersatisfaction  purchaseintent
0               NaN                  2                     1               0
2               NaN                  1                     5               1
8               NaN                  3                     4               1
10              NaN                  1                     3               0
12              NaN                  1                     3               0
...             ...                ...                   ...             ...
8972            NaN                  2                     3               1
8976            NaN                  3                     3               0
8991            NaN                  2                     5               1
8994            NaN                  1                     3               0
8998            NaN                  4                     2               1

[1863 rows x 9 columns]

In [65]:
print(df[df['customerage'] > 50])

      productid productcategory productbrand  productprice  customerage  \
2          5876         Tablets      Samsung           NaN           63
3          5877     Smartphones      Samsung           NaN           63
4          5878         Tablets         Sony           NaN           57
9          5883         Laptops           HP           NaN           66
13         5887      Headphones         Sony           NaN           62
...         ...             ...          ...           ...          ...
8988      14862   Smart Watches         Sony           NaN           63
8990      14864      Headphones      Samsung           NaN           69
8992      14866         Tablets         Sony           NaN           61
8996      14870     Smartphones      Samsung           NaN           57
8999      14873     Smartphones         Sony           NaN           62

     customergender  purchasefrequency  customersatisfaction  purchaseintent
2               NaN                  1                     5               1
3               NaN                 10                     3               1
4               NaN                 17                     3               0
9               NaN                  8                     4               1
13              NaN                  2                     5               1
...             ...                ...                   ...             ...
8988            NaN                 16                     4               0
8990            NaN                 16                     3               1
8992            NaN                 12                     4               1
8996            NaN                  5                     1               1
8999            NaN                 15                     2               1

[3297 rows x 9 columns]

In [67]:
print(df['purchasefrequency'].isnull().sum())
print(df['customerage'].isnull().sum())

0
0

In [ ]:
# Short Summary of Changes:
#1.Removed duplicate rows to ensure unique records.

#2.Checked and handled missing values where necessary.

#3.Mapped numeric gender codes to text labels (e.g., 0 → Male, 1 → Female).

#4.Standardized column names to lowercase with underscores for consistency.

#5.Checked and fixed data types for numeric columns.

#6.Verified data integrity with basic outlier checks.

#7.Saved the cleaned dataset for further analysis.